services:
  - type: web
    name: file-sharing-api
    runtime: python311
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --worker-class sync --timeout 120
    envVars:
      - key: DEBUG
        value: 'false'
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: '*.render.com'
      - key: DATABASE_URL
        sync: false

  - type: pserv
    name: file-sharing-redis
    runtime: redis7
    disk:
      name: redis_data
      mountPath: /var/lib/redis
      sizeGB: 1
