# Generated by Django 5.1.3 on 2026-06-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_stateless_tokens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharelink',
            options={'ordering': ['-created_at']},
        ),
    ]
